### ISSUE TITLE
libgmp's inline asm, which is seven templates and six instructions this compiler does not have

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc#1329]
## What

libgmp does not build with rucc, and the first thing it stops on is not the hand written assembly, which now assembles and disassembles the same as gas in all sixty two files. It is the inline assembly in `longlong.h`, which every file in the library includes and which is where libgmp writes the six operations a bignum library is made of.

```
libgmp at O0
  outcome      did not build
  reached      configured
  seconds      107.32 building, 0.00 testing
  baseline     173 under gcc
  first error  divis.c:116:3: error: cannot generate code for '__gmpn_divisible_p': this `asm` has instructions in its template, which nothing here assembles [E0653]
```

## The six templates

They are `longlong.h` lines 1036 to 1102, inside `#if defined (__amd64__) && W_TYPE_SIZE == 64`, and there is one more in `gmp-impl.h`.

```
add_ssaaaa              "addq %5,%q1\n\tadcq %3,%q0"
sub_ddmmss              "subq %5,%q1\n\tsbbq %3,%q0"
umul_ppmm               "mulq\t%3"
udiv_qrnnd              "divq %4"
count_leading_zeros     "rep;bsr\t%1, %q0"
count_trailing_zeros    "rep;bsf\t%1, %q0"
BSWAP_LIMB              "bswap %q0"
```

Nothing else in the library reaches an x86-64 template. `ULONG_PARITY` writes `xorb %h1, %b1` but is behind `HAVE_HOST_CPU_FAMILY_x86`, which is off on this target, and the two string move templates in `gmp-impl.h` are behind `#if 0` with a comment saying they were never checked to be an improvement.

## What is actually missing

Each of those seven templates was compiled on its own against a fresh rucc on server3, so this is measured rather than read off the manual.

The first gap is the operand size modifier. `movq %1, %q0` is refused and `movq\t%1, %0` is taken, which says the reader gets as far as the sigil and then finds a letter where it expects either a digit or a register name. `crates/rucc-target/src/x86_64/read.rs` reads `%0` as an operand and `%rax` as a register and has nothing in between. gcc's `%q`, `%k`, `%w` and `%b` say which part of the operand's register to write, and libgmp uses `%q` throughout because `longlong.h` is shared with the thirty two bit target and the suffix on the mnemonic is not enough on its own.

The second gap is that six instructions have encoder rows and no machine opcode. `crates/rucc-target/src/x86_64/encode.rs` knows how to write the bytes of `adcq`, `sbbq`, `bsfq` and `bsrq`, because tamnd/rucc#1305 put them in for the hand written files, but `crates/rucc-target/src/x86_64/insts.rs` has no opcode with those names, and the machine IR listing is what `x86_64::read` searches. An encoder row is how an instruction is written down and a machine opcode is what the allocator is told about, and a template needs both.

The one operand multiply and the one operand divide are missing in a different way. There is no unsigned widening multiply at all: `imul_rr_64` is the two-address one that keeps the low half, and a library that multiplies two limbs wants both halves. And `div_quo_64` and `div_rem_64` are each two instructions, a clear and then the divide, so neither of them is the single `divq` a template writes, and neither of them has both answers: `udiv_qrnnd` wants the quotient and the remainder out of one instruction.

`bswap` has no opcode either. `__builtin_bswap64` is expanded into shifts and masks in `crates/rucc-codegen/src/expand.rs`, the same trade tamnd/rucc#310 describes for the bit counts, so nothing in the backend has ever needed the instruction.

The `rep` prefix in front of `bsr` and `bsf` is how a program spells `lzcnt` and `tzcnt` for an assembler older than those mnemonics, and on a processor without the feature the prefix is ignored and the old instruction runs. `read.rs` takes a repeat prefix in front of exactly one thing today, which is `nop`, because `rep nop` is `pause`. These are the second and third.

## The one that needs a decision rather than a row

`adc` and `sbb` read the carry the instruction in front of them set, and the head of `insts.rs` says that nothing in that description mentions flags and that this is a deliberate constraint rather than a simplification. A template is where that constraint meets a program that wrote two instructions meaning them to be a pair. So the work here is not only adding an opcode, it is saying what keeps the pair a pair once the two halves are separate machine instructions in a block, and checking that nothing between lowering and emission can put anything in between them or move them apart.

## Checklist

- [x] The operand size modifiers `%q`, `%k`, `%w` and `%b`, read in `crates/rucc-target/src/x86_64/read.rs`
- [x] `bsf` and `bsr` as machine opcodes, with the repeat prefix in front of them read as the count it spells rather than as the same instruction
- [x] `bswap` as a machine opcode
- [x] The one operand unsigned multiply, which writes both halves
- [x] The one operand unsigned divide, which writes the quotient and the remainder
- [x] `adc` and `sbb`, with the pair written down as a pair
- [x] The seven templates above compiling and running, checked against gcc 16.2.0 rather than against a reading of the manual
- [x] A label in a template and a jump back to it, which is the loop `MPN_IORD_U` writes and is what `MPN_INCR_U` and `MPN_DECR_U` are
- [x] `sbb %q0, %q0`, which reads an operand the statement declared as an output and nothing else, and is `add_mssaaaa` in `div_qr_1n_pi1.c` and `mod_1_1.c`
- [x] `adc $0, %q0`, the add with carry against a constant, which is `add_sssaaaa` in `div_qr_2.c` and its neighbours
- [x] `jmp *72(%r8,%rsi,8)` in the assembler rather than in a template, which is the jump table in `mpn/mod_34lsub1.asm` and is what the build stops on now
- [x] The seven instructions `tests/amd64call.asm` writes, which is what the suite stopped on: a constant straight into memory, a push and a pop with no width letter, `pushf` and `popf`, `call *(%rax)`, and the three x87 instructions written with `fwait` in front of them
- [x] libgmp building with rucc and its suite running. The library builds, the suite builds and runs, and the whole of it passes: a hundred and seventy seven tests pass, one is skipped, nothing fails and nothing errors. The last thing in the way was tamnd/rucc#1424, which was a fold in the back end rather than anything about assembly

**Comment by tamnd** [comment]
The first box is done, in tamnd/rucc#1330. `%b0`, `%w0`, `%k0` and `%q0` are read, they are what the suffix a template left off is worked out from when there is one, and a width that disagrees with the mnemonic or with the type of the operand is refused rather than one half being believed over the other. `%h` stays out and stays refused, since it names a register rather than a part of one and nothing on this target reaches it.

Next is the pair of searches. `bsf` and `bsr` have encoder rows from tamnd/rucc#1305 and no machine opcode, and the repeat prefix in front of them is not a decoration: libgmp's own comment says "This is lzcnt, spelled for older assemblers", so `rep;bsr` is a different instruction from `bsr` on every processor built in the last fifteen years and writing the plain one would be a program that does something other than what it says. That means four opcodes rather than two, and the prefixed pair needs encoder rows as well, which gas writes as `f3 0f bd` and `f3 0f bc".

**Comment by tamnd** [comment]
Second box done in tamnd/rucc#1334, merged. `bsf` and `bsr` are machine opcodes at all three widths the machine has them at, and `lzcnt` and `tzcnt` are opcodes at the two widths this assembler has an encoding for.

The box as I wrote it said the repeat prefix should be read as the same instruction, and that turned out to be wrong, so the box now says what the pull request does instead. `rep;bsr` is not `bsr` with a decoration in front of it. It is `lzcnt`, spelled the way an assembler older than that mnemonic would take it, and libgmp's own comment beside the line says exactly that. The two answer different questions: on a sixty four bit limb with the top bit set, the search answers sixty three and the count answers zero. Reading the prefixed line as the bare one would have been a program that quietly computes something else, which is worse than refusing it. So there are four families here rather than two, and the prefixed pair needed encoder rows of their own, which gas writes as `f3 0f bd` and `f3 0f bc`. The sixteen bit count is refused, because gas writes it with two prefixes and no size in this encoder says more than one.

Two things came out of writing it that were not in the plan. The first is that these are a form of their own rather than the conversions they share an operand vector with. `Form::Convert` is what `BITS` reads to say an instruction copies the low bits of its source, and it is on the list of forms that leave the condition state alone, and both of those are false of a search: what it writes is a position or a population rather than any part of the source, and every one of them writes the state. Describing one as a conversion would have been a wrong answer to two passes rather than a tidy reuse of a shape.

The second is that no rule selects any of the ten, and that is deliberate rather than a gap to fill later. `rucc_codegen::expand` already answers both questions out of arithmetic every machine has, and it does that because what these instructions do when their source is zero differs between families of processor. A rule that selected one would be a rule whose answer depends on what ran it. They get an exemption category of their own in the selector's reachability check, with a test that reads both ways round, so the list cannot grow an opcode the machine does not describe as a search and a search added later cannot go unselected with nobody saying why.

The bytes were checked against gas on gcc 16.2.0 rather than against the manual, all six register forms and both memory forms. The end to end tests compile the three templates libgmp actually writes, with the `rm` constraint the header uses.

One thing worth knowing about that pull request beyond its own subject. tamnd/rucc#1333 was squashed from a branch whose tree had deleted work already on main, which took tamnd/rucc#1330 back out along with two other pull requests, so the first box of this issue had quietly stopped being true. tamnd/rucc#1334 puts it back, since it is built on top of it. The other two are tamnd/rucc#1335.

Next is `bswap`, which is the smallest thing left on the list: one opcode at two widths, encoder rows that already exist from tamnd/rucc#1305, and nothing about flags or pairs to decide.

**Comment by tamnd** [comment]
tamnd/rucc#1348 is in, so the third box is ticked: `bswap` is a machine opcode now, at the two widths the machine has a defined answer for.

The part of the issue text about this one was half wrong and it is worth saying which half. I wrote that `bswap` has no opcode, which was right, and I assumed the encoder rows were already there from tamnd/rucc#1305 the way `adcq` and `sbbq` are. They were not. There were no bytes for it anywhere, which is why three tests in this tree used `bswap` as their example of an instruction this compiler refuses by name. So this one needed both halves rather than one, and the four byte strings in the encoder test were taken from gas on server3 rather than read off a table: `bswap %eax` is `0f c8`, `bswap %rax` is `48 0f c8`, `bswap %edx` is `0f ca`, and `bswap %r12` is `49 0f cc`. The register sits in the low three bits of the second opcode byte rather than in an addressing byte, the same way a push and a pop hold theirs, so there is no ModRM on one of these.

Two widths and not three. `bswap %ax` assembles and Intel's own description says the result is undefined, so the instruction exists and means nothing, and a program that wants two bytes the other way round writes a rotate by eight.

The thing that took the most thought was not the bytes. It was whether this is a unary operation. It has the same operand vector as a negate or a complement, one register read and written in place, and the obvious move is to reuse `Form::UnaryR`. The reason not to is that `bswap` leaves the condition state exactly as it found it, and every other instruction of that shape writes it. The default in this target is that an unknown name writes the flags, which is the safe way round, so calling it a unary operation would not have produced a wrong program. It would have been a claim the manual does not make, and a form is supposed to be what the manual says rather than what saves a line, so it got `Form::Swap` and a place on the exempt list in `writes_flags`. It is the only entry on that list that computes anything: everything else there is a move, a jump or a nop.

That leaves four boxes of machine work. Next up are the one operand multiply and the one operand divide, which are the same shape of problem as each other: both write two registers out of one instruction, and this compiler has no instruction that does that today. `div_quo_64` and `div_rem_64` are each a clear and then a divide, and they each throw one of the two answers away, which is exactly what `udiv_qrnnd` wants kept. I will take the multiply first because it has no exception cases, then the divide, and leave `adc` and `sbb` for last since those need the pair decision rather than a table row.

**Comment by tamnd** [comment]
tamnd/rucc#1353 is in, so the fourth box is ticked. The one operand multiply is a machine opcode now, signed and unsigned, at the three widths where it writes a pair of registers.

The table part was the easy half and it went the way the last two did: a form of its own, `Form::MulWide`, with one multiplicand and both halves of the answer fixed to registers the opcode carries and the other multiplicand the one thing the text names. It is the same operand vector a division has read the other way round, and the single thing that differs between them is worth having written down. A division writes `rdx` early, because the sign extension that fills it runs in front of the divide and the divisor may therefore not be sitting in it. Nothing runs in front of a multiply. So both definitions here are ordinary ones, which is what lets the second multiplicand be allocated to `rdx` and still be read, and calling it early would have cost a register on every one of these for a hazard that does not exist.

Three widths and not four. The eight bit form is a different instruction wearing the same name: its answer is sixteen bits and both halves of it live in `ax`, so it writes one register where these write two. It keeps the encoder rows it has had since tamnd/rucc#1305 and it gets an opcode on the day something reaches it.

The half I had not seen coming is the tie, and it is the reason this issue's remaining boxes are not just table rows either. `umul_ppmm` is written `"=a" (w0), "=d" (w1) : "%0" (u), "rm" (v)`. The instruction reads `rax` without its text naming it, and what says the program's value is in `rax` is split across two operands: the letter is on the output, which has no value to read, and the value is on the input, which has no letter. Reading only the letter found an output with nothing to read and gave up, and what a template operand gets when nothing is found for it is a register of its own with a zero put in it. That is not a refusal, it is a library that multiplies every pair of limbs to nothing. A read of a fixed register now follows the tie to the input that fills it.

I checked it by running it rather than by reading the listing, which is what that near miss argues for. Six pairs of limbs through `umul_ppmm` on server3, including both extremes and a pair whose product needs every one of the hundred and twenty eight bits, compiled by rucc at `-O0`, `-O1`, `-O2`, `-O3` and `-Os`, each run agreeing with gcc 16.2.0 byte for byte and with the compiler's own `__int128` answer. The signed `imulq` and the narrow `mull` and `mulw` were checked the same way at two levels.

Next is `udiv_qrnnd`, which is the same shape again and takes the tie work with it: `"=a" (q), "=d" (r) : "0" (n0), "1" (n1), "rm" (dx)` is two ties rather than one, and both of them are now read. What is new there is that the dividend is genuinely two registers the program filled, where the two divides this compiler has today fill the high half themselves and write it early. So it is a fifth operand and a form that reads what the others clobber, rather than anything about how a template is read.

**Comment by tamnd** [comment]
Fifth box ticked. #1361 is merged, which is `udiv_qrnnd`, and it is the multiply in #1353 undone.

What is new about it is one operand. The two divides this compiler already had are each two instructions, because a division in C divides a number by a number of its own width while the machine divides a pair, so the compiler fills the high half itself and then divides, and because it fills it the high half is a register written early. A program doing long division a limb at a time filled it already, so here the same register is a fourth operand the form reads. Saying it is written early instead would tell the allocator that half the dividend is gone before the operands are read, which is a lie about the one register that carries it. Five operands, which is the widest thing this target describes that is not the question put to the processor, and three widths not four for the same reason the multiply has three: the byte divide keeps its dividend and both its answers in `ax`, so it is one register where these are a pair. That leaves the byte divide as the only divide this compiler still writes as more than one instruction, and the reader's refusal test now names it rather than the quad one.

The tie work the last box was expecting turned out to be nothing, because the multiply had already done it. `"=a" (q), "=d" (r) : "0" (n0), "1" (n1), "rm" (dx)` is two ties rather than one, and both of them are read by the rule that landed with the multiply, so this branch is a form, a table row at three widths, a text spelling and the timing.

Checked by running. A program built around this repository's target of the exact `udiv_qrnnd` and `sdiv_qrnnd` macros, over eight triples including both extremes, a dividend that needs all 128 bits, a signed case and a loop of sixty four divides whose two answers are both used, compiled by rucc at `-O0`, `-O1`, `-O2`, `-O3` and `-Os`. All five agree with gcc 16.2.0 line for line, and the program also checks each answer against the compiler's own `__int128` division and multiplies it back. Gate green on server3 in 504s.

Next is `adc` and `sbb`, which is the last of the seven templates and is not a table row. `add_ssaaaa` and `sub_ddmmss` each write two instructions that pass a flag between them, and the header on `crates/rucc-target/src/x86_64/insts.rs` says nothing in that table mentions flags and that this is deliberate, so the question is how to keep a pair a pair once the two halves are separate instructions in a block, rather than how to spell either one.

**Comment by tamnd** [comment]
Sixth box ticked, and with it every instruction on the list. #1366 is merged, which is `adc` and `sbb`.

This one was not a table row, and the reason is worth keeping. The bit passed from the add to the add with carry is not a register, so nothing in an operand vector says the second waits for the first, and the header on the instruction description says nothing there mentions flags and that this is deliberate. It still says that. What keeps the pair a pair is the description of the condition state next door, which is the list the scheduler builds its dependence edges from, and these two are on it now. So nothing that writes the flags may move between the halves and the second half may not move in front of the first.

What they read is a fourth group, `Reads::Carry`, because the other three are parts of the answer to a comparison and this is not one. A jump after an `and` may read what the `and` left. Nothing leaves the bit an add with carry wants except the addition in front of it, so the new group answers no to every entry in the table of what arithmetic leaves behind and will go on answering no to entries added later. That made the comparison redundancy pass the thing that had to be right, and it was not quite: it asked whether an instruction writes the condition state before asking what it reads, which for the one instruction that does both would have ended the walk without ever counting the carry it took. The two questions are now asked in that order.

One more thing came out of writing the test, and it is the multiply's fix seen from the other side. `umul_ppmm` reaches `rax` by a constraint letter and says what is in it with `"%0"` on an input, and #1353 taught the letter lookup to follow that tie. `add_ssaaaa` reaches its first source by numbering the output in the template and says what is in it with `"0"` on an input in exactly the same way, and that path still refused, because an output written `=` has no value of its own. It follows the tie now too. An output nothing is tied to still refuses, which is the case the existing refusal test pins.

Checked by running, over eight pairs of 128 bit values including a carry out of the top and a borrow into it, and a chain of a thousand additions with other work in between so the pair has to survive being surrounded. Five levels, all agreeing with gcc 16.2.0 and with the compiler's own `__int128` arithmetic. Gate green on server3 in 391s.

That is all seven templates: the four size modifiers, the two searches with the repeat prefix in front of them, the byte reversal, the multiply that keeps both halves, the divide that keeps both answers, and now the pair. Next is the box under this one, which is the seven of them together in one file rather than one at a time, and then libgmp itself.

**Comment by tamnd** [comment]
Seventh box ticked. The seven templates are in one file now rather than one at a time, taken from `longlong.h` as written, and the file builds and runs under both compilers on server3.

Nine macros, since two of the seven have two spellings each and libgmp picks between them on what the processor the build was configured for can do. `add_ssaaaa`, `sub_ddmmss`, `umul_ppmm`, `udiv_qrnnd`, `BSWAP_LIMB`, `count_leading_zeros` and `count_trailing_zeros` with the plain `bsr` and `bsf`, and the same two counts with the repeat prefix in front of them, which is the older assembler's way of writing `lzcnt` and `tzcnt`.

Writing it caught one thing, and it was my harness rather than either compiler. The prefixed spelling is a different instruction, not a different name for the same one: `bsr` gives the index of the highest set bit and libgmp turns that into a count with `^ 63`, while `lzcnt` gives the count already. I applied the `^ 63` to both at first, and rucc and gcc both printed the same wrong number, which is the useful kind of failure. Each spelling now checks against its own answer and the two are checked against each other.

Twelve values through the single operand macros and all 144 pairs of them through the multiply, the add, the subtract and the divide, with the divide given the promise its comment asks for, which is a divisor larger than the high half of the dividend. Every answer is checked against the compiler's own `__int128` arithmetic and against `__builtin_clzl`, `__builtin_ctzl` and `__builtin_bswap64`. Built at `-O0`, `-O1`, `-O2`, `-O3` and `-Os` with rucc and with gcc 16.2.0, and all ten runs print the same 300 lines.

The listing has all seven: `bsrq`, `bsfq`, `lzcntq`, `tzcntq`, `bswapq`, `mulq`, `divq` and an `adcq` and `sbbq` each sitting behind the `addq` and `subq` they read a bit from.

Next is the last box, which is libgmp itself.

**Comment by tamnd** [comment]
#1375 is merged, which takes libgmp past `divis.c`.

What stopped it was the template the library writes wherever it counts the zero bits at either end of a limb. The count goes into an `unsigned`, since a count of the bits of a limb cannot exceed sixty four, and `longlong.h` still spells the destination `%q0` because the same line is read on the target where a limb is a `long`. The width the template wrote and the width the type says therefore disagree, and where the operand is placed that was refused outright on the grounds that handing an instruction the top half of a register nothing defined is a program that assembles into something other than what it says. That grounds is about a read. On a write there is nothing undefined anywhere: the instruction fills the whole register and the object is the low part of what it filled. The refusal is now the read's alone, and a written operand narrower than its type is still refused because that one does leave the top of the object holding whatever the register held before.

The library now builds as far as `mpn/generic/fib2_ui.c`, which asks for something else. `MPN_INCR_U` in `gmp-impl.h` is a template with labels in it and jumps to those labels, a memory destination, and a displacement taken from a constant operand through `%c`. That is the next piece of work and it is a larger one than the seven templates were, because a jump inside a template is control flow inside what the block layout thinks is one block, so the honest lowering splits the block at the template's labels rather than hiding a branch inside one.

The seven templates are all read and all checked against gcc 16.2.0 at five levels. What is left before the last box is this eighth shape.

**Comment by tamnd** [comment]
tamnd/rucc#1376 landed, which is the first of the two pieces `MPN_INCR_U` needs.

A template writes `%c3(%0)` when the distance into an address is a size something else worked out. libgmp writes one wherever it steps a pointer along by one limb, and the reason the size is an operand rather than a number in the line is that the same header is read on the target where a limb is four bytes: `sizeof(mp_limb_t)` is tied to an `"n"` operand and the template names that operand where the distance goes. The reader now says which of the two a displacement is, a number it read or an operand it was pointed at, and the placement resolves the second from the constant that operand's value was defined by. An operand no instruction of the template ever names is no longer given a register either, which is what a distance is: the number is written into the instruction, so a copy of it in a register would be one nobody reads.

What is left of `MPN_IORD_U` is the labels and the jumps to them, which is the whole reason that macro is a loop. The shape is a label at the top, an add or a subtract into memory, a `lea` that steps the pointer by the distance above, and a `jc` back to the label. Reading that means splitting the statement into machine blocks at the labels and ending a block with a jump that reads the condition state directly, which nothing does yet: the block layout only knows the branch that reads a register and the rewrite that folds a comparison into it. The pointer is written inside the loop and read at the top of it, so the operand it is in becomes a parameter of the block the label made, and each jump carries the register it has at that point. That is the next piece of work.

The count of what is in the way is unchanged until it lands. A full build of libgmp with rucc gives one distinct diagnostic across the whole library, 154 times in 112 files, and 64 of those are `MPN_INCR_U` and `MPN_DECR_U`.

**Comment by tamnd** [comment]
#1394 is merged, and with it the last of libgmp's inline assembly that this backend had no shape for at all.

What it reads is a label in a template and a jump back to it, which is `MPN_IORD_U` in `gmp-impl.h`: a place named at the top, an add or a subtract of one into the word the pointer is at, a `lea` that steps the pointer along by one limb, and a `jc` back to the place, which carries a one into the next word for as long as the word before it wrapped. `MPN_INCR_U` and `MPN_DECR_U` are that macro with the mnemonic filled in, and between them they were most of what the library was collecting refusals for.

A template that jumps cannot stay one instruction of the IR, so the statement is taken apart where it is lowered. Each label becomes a block, each jump ends the block it stands in and gives it the label's block and a fresh one as its two arms, and whatever follows the statement goes into whichever block the walk finished in. Doing it in the lowering rather than earlier is the decision, and the reason is the condition state: the instruction that sets it and the jump that reads it are written next to each other by the program with no value between them that an IR statement could carry, so a pass that split the template into separate statements before the machine level would put a boundary exactly where the program needs none. At the machine level the two are instructions in one block, the scheduler already refuses to move anything that writes the flags between an instruction and a reader of them, and a move is all the allocator may put between them, which on this machine leaves the flags alone.

The machine IR is in the form where a register is written once, so the pointer written inside the loop and read again at the top of it cannot be one register. Every block a label made takes one parameter for each operand that is in a register at all, in one fixed order, and every jump carries whichever register held the operand where the jump stands, so an arm's arguments and a block's parameters are the same list read twice. The back edge is a critical edge and the pass that already splits those gives it a block of its own, which is what keeps the moves an arm turns into behind the jump rather than in front of it.

Both forms of the macro were compiled and run against gcc 16.2.0 on server3, over a limb that wraps, a limb that does not, and a carry that runs off the end of the first word into the second, and the two compilers print the same numbers.

Every C file libgmp has was then compiled one at a time at `-O2`, which is 1,012 of them. Nine refusals over an `asm` statement are left where there were a hundred and fifty four over a hundred and twelve files before this, and not one of the nine is a label or a jump. They are two shapes rather than nine, and they are now boxes on the checklist above:

- Five are `add_mssaaaa` in `div_qr_1n_pi1.c` and `mod_1_1.c` writing `sbb %q0, %q0`, which reads an operand the statement declared as an output and nothing else. The value it reads is undefined and the program does not care, because what `sbb x, x` is for is the carry bit rather than the number.
- Four are `add_sssaaaa` in `div_qr_2.c` and its neighbours writing `adc $0, %q0`, which is the add with carry against a constant. The register form landed earlier and the constant form is a row the table has not got yet.

The build itself now stops somewhere else entirely, on `mpn/mod_34lsub1.asm`. That is hand written assembly rather than a template, and what it stops on is `jmp *72(%r8,%rsi,8)`, an indirect jump through a table. So libgmp is no longer waiting on the `asm` statement for its next step, it is waiting on the assembler, which is a third box above.

`spec/11-asm-objects-debug.md` section 11.2 now says what is read and what is refused, which is a jump with no condition on it, a condition this machine has no opcode for, one name given to two labels, and a jump to a name no label in the template defines.

One thing found along the way and not fixed here: `cargo xtask accounting` has a flake. `an-adopted-arena-carved-into-objects-that-fit` at `-O2` segfaults on about one run in four, and it does so on `main` as well as on the branch, measured five runs each side. It is not this change and it deserves an issue of its own.

**Comment by tamnd** [comment]
#1406 is merged, and with it libgmp's inline assembly is finished. Every one of the library's 1,012 C files compiles at `-O2` with no refusal over an `asm` statement, where there were nine before this and a hundred and fifty four over a hundred and twelve files before the label work in #1394.

The two shapes were the ones named in the comment above. `adc $0, %q0` is the add with carry against a constant, which `add_sssaaaa` writes for the top word of a number three words wide, and it needed a form of its own rather than a reuse of the register form's: the list of instructions that read the condition state is derived from the forms rather than typed out, so an instruction that reads the state has to be findable by its form, and a form carrying an immediate is a different operand vector from one that does not. It brings eight opcodes, `adc` and `sbb` at each of the four widths, and the encoder already had the bytes for all eight.

`sbb %q0, %q0` is an output the template also reads. rucc refused it on the grounds that reading something nothing filled is a mistake, and that is not this compiler's mistake to call. The program said it does not care by writing `=` rather than `+`, and gcc 16.2.0 accepts the same statement without a word and adds whatever the register it picked was holding, which I checked rather than assumed. So it is accepted, and the operand gets a register holding a zero, which is the answer an output nothing wrote already got. The zero is worth having rather than merely legal: the tie that reuses the input register lands the write where the zero is, so `sbb x, x` gives exactly the borrow bit sign extended, which is the number the macro wants.

Both were run against gcc 16.2.0 at runtime rather than only compiled, `add_sssaaaa` over five inputs and `add_mssaaaa` over six, and the two compilers print the same numbers.

That leaves the two boxes at the bottom of the list, and both are outside the C. The next one is `jmp *72(%r8,%rsi,8)` in the assembler, which is the jump table in `mpn/mod_34lsub1.asm` and is where the build stops now.

**Comment by tamnd** [comment]
#1409 is merged and libgmp builds. The library compiles and links with rucc end to end, which is every C file it has and every hand written assembly file it has, and it is the first project of this size on the R2 rung to get there.

What it took was one row of the encoding table. `jmp *72(%r8,%rsi,8)` in `mpn/x86_64/mod_34lsub1.asm` is a jump table, and the jump through a register was already there while the jump through an address was not. A compiler that owns both halves loads the entry into a register and jumps through the register, so the row was never needed until a file somebody else wrote by hand came along. The five bytes rucc writes for that line are the five gas writes for it.

Comparing rucc's object for that file against gas's, the jump is identical and the only differences left are the two already known: a conditional branch taking six bytes where gas takes two, which is #1284, and the padding an alignment writes, which follows from it.

The suite does not run yet, and what stops it is in the suite rather than in the library. `tests/amd64call.asm` writes a constant into memory with `movq $0, -8(%rsp)`, which is another row the table has not got. That is the next thing, and it is the last box on this issue with anything before it.

**Comment by tamnd** [comment]
#1426 is merged, and with it libgmp's own test suite builds and runs under rucc.

What was missing was seven instructions that only a file written by hand writes. `tests/amd64call.asm` calls a function and then checks that every register the calling convention says the function had to leave alone was left alone, which is a thing you cannot write in C, so it writes a constant straight into memory, a push and a pop with no width letter on them, `pushf` and `popf`, a call through an address, and three x87 instructions with `fwait` in front of them. All seven were checked against gas rather than against a reading of the manual, and rucc's object for the whole file is byte for byte what gas writes for it except that one alignment is filled with two one byte nops instead of one two byte nop.

The `fwait` forms had the only real decision in them. `fstcw` is `fwait` followed by `fnstcw`, and the tempting thing is to give the waiting row a two byte opcode starting with the wait. That is wrong in a way that assembles and runs: the writer puts the REX byte in front of the whole opcode, so the wait would end up behind it and the REX byte would be about the wait rather than about the store. On `fstcw (%r8)` that is a store to the wrong address. So a row says whether it is written with a wait and the writer puts that byte down first, and there is a test holding `fstcw (%r8)` as `9b 41 d9 38`.

Where the suite stands. The eight tests in the top level directory pass, and so do thirty of the thirty one in `tests/mpn` that the run reached. The run stops on the thirty first, `t-div`, which GCC 16 finishes in 5.8 seconds and which rucc leaves spinning at full processor for as long as it is left alone. That is not the assembler and it is not the time limit in the manifest, which is what the last comment here guessed at. It is a miscompile, and it is filed as #1424 with the cause found.

Briefly, since it is the thing standing between here and the last box. It was found by building the library twice, once with rucc and once with GCC 16, and then relinking rucc's library with one object at a time taken from the GCC build until the test passed. One object matters out of 210, which is `mpn/mulmod_bnm1.o`. Compiling that file alone at `-O0` fixes it and `-O1` does not, `-fno-number` fixes it, and `-fpass-fuel-global` says the file is correct after 721 rewrites and wrong after 722. The two objects differ by eight instructions in one block. The value numbering removes a second computation of `n - 1` because a register already holds it, which is true and fine, and that lets a load, an add and a store to what is now one address fold into a single add to memory. Folding them moves the add down to where the store was, and sitting between the two was `adcq %rdx, %rdx`, which is how this back end captures the carry out of an addition. So the carry reader now runs in front of the add that makes the carry and reads what a `subq` left behind instead, and one limb of the wrapped product goes in wrong, which leaves `mpn_preinv_mu_div_qr` with a remainder it cannot count down from and a loop with no other way out.

So the remaining box is a back end fix rather than more rows in the encoding table, and the instructions half of this issue is done.

**Comment by tamnd** [comment]
libgmp is done. The library builds with rucc, the suite builds with rucc, and the whole suite passes: a hundred and seventy seven tests pass, one is skipped, nothing fails and nothing errors, at -O2, on a host with GCC 16.2.0 beside it for comparison.

The last thing in the way was tamnd/rucc#1424, fixed in tamnd/rucc#1433, and it was not about assembly at all. `rucc_codegen::combine` turns a load, an arithmetic instruction and a store into the one instruction this machine has for all three, and the instruction that comes out sits where the store was, so the arithmetic moves down the block and takes the condition state with it. Nothing checked what it moved past. `mpn_mulmod_bnm1` adds a limb into a place and takes the carry out of that addition with the `adcq %rdx, %rdx` that `add_ssaaaa` asks for, and that carry reader was sitting between the addition and the store, so the fold put the addition below it and the carry that went into the next limb was the one a `subq` three instructions earlier had left. The library computed a product wrong in one limb and it came back as `tests/mpn/t-div` never finishing, a test GCC 16 runs in 5.8 seconds. It finishes in 10.5 seconds now.

Finding it was the slow part and is worth writing down for the next one. Swapping one object at a time out of the library rucc built for the one GCC built named `mpn/mulmod_bnm1.o` on its own, rebuilding that file at each optimization level said -O0 was fine and -O1 was not, and halving `-fpass-fuel-global` until one rewrite was left said 722, which is the hundred and seventy first time the numbering pass removed an instruction an earlier one in the block already computed. That removal is what put the load, the add and the store next to each other, and the fold that follows is what moved the add. Three tools, each one narrowing by a factor, and the whole chain from a hung test to a named rewrite is a few hours rather than a reading of the output.

So every box on this issue is ticked. What that covers is the thirteen assembly shapes libgmp writes across its sources and its own test suite, from the two operand forms in `longlong.h` through the label and the jump back to it in `MPN_IORD_U`, the jump table in `mpn/mod_34lsub1.asm`, and the seven instructions `tests/amd64call.asm` writes to check the calling convention.

**Comment by tamnd** [comment]
Every box is ticked and libgmp's suite passes end to end, so this is done.
