### ISSUE TITLE
__int128 is turned off above -O0 by the order the blocks were made in

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc#1054]
jtckdint fails above `-O0` and it is not only the compile time. It ends with

```
test.c:115:3: error: cannot generate code for 'main': no rule lowers a `load` producing a `i128` [E0653]
```

at `-O1`, `-O2` and `-Os`, and compiles clean at `-O0`. So even a compile that came in under the corpus cell timeout would still fail the cell, and the timeout work in #1045 is not the whole of what R0 needs from this program.

A reduced version of the file, jtckdint's own `test.c` with the type table cut down to `MMM(int128_t)`, reproduces it in a few seconds and reports `zext` rather than `load`, which is the same thing: whichever instruction at that width the selector reaches first is the one it names.

## What is wrong

`rucc_codegen::wide` is the pass that turns every 128 bit integer into a pair of 64 bit halves, so that nothing below it ever sees a width the machine has no register for. It is all or nothing on a function: it first asks whether it understands every instruction, and if any answer is no the whole function is left alone and the selector refuses the first wide instruction it meets.

One of the things it asks is that a wide value's definition come before its use. It reads that against a list of instructions built by walking `func.blocks()`, which is the order the blocks were made in, and not the order they run in.

At `-O0` those two orders mostly agree, because the front end makes a block when it reaches it. Above `-O0` they do not, because every optimizer pass that makes a block appends it: a preheader for a loop, a copy of a header put in front of one, a block split off an exit. All of those run early and are made late. So a use ends up ahead of its definition in that list, the pass says it does not understand the function, and the program is refused for a reason that has nothing to do with what is in it.

Instrumenting the refusal on the reduced file gives exactly one complaint in a function of about ten thousand instructions:

```
WIDE-REFUSE: use before def, user Add at 10207
```

One instruction in the wrong place in a list turns off `__int128` support for the whole function.

## The fix

Walk the blocks in reverse postorder from the entry instead. A value is defined in a block that dominates every block reading it, a dominator is on every path from the entry, so a depth first walk finishes it last and reverse postorder puts it first. Blocks nothing reaches go at the end in the order the function holds them, since deciding a block is unreachable is not this pass's business.

The check itself stays. It is cheap, it still covers the unreachable blocks, and a pass whose correctness rests on an ordering should say so rather than assume it.

## What done means

jtckdint compiles at `-O1`, `-O2` and `-Os` rather than being refused, and a test in the pass builds a function whose blocks are made in the order the optimizer produces and asserts the split still happens.
