### ISSUE TITLE
Vector types built with the vector_size attribute are not supported

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc#200]
A type built with `__attribute__((vector_size (N)))` is not a vector type here. The attribute is parsed and dropped, so the declaration gives an ordinary scalar or array and everything written on it afterwards is refused:

```c
typedef unsigned V __attribute__ ((__vector_size__ (sizeof (unsigned) * 2)));

void foo (V *v, V *w) { *w = -*v / 11; }
```

```
error: subscripted value is neither array nor pointer nor vector [E0504]
```

The message already says "nor vector", so the checker knows what a vector type is. What is missing is the attribute that makes one, and with it the operations on the type: the arithmetic and bitwise operators applied element by element, the comparisons that give a vector of masks, subscripting, the vector compound literal in a static initializer, `__builtin_shuffle` and `__builtin_shufflevector`, and the conversions between two vector types of one size.

Forty four files in the gcc.c-torture execution suite use `vector_size` and thirty three of them fail on it, which makes this the largest thing in that suite after the missing builtins and the old style definitions in #100. Real code reaches for it too, since it is how portable SIMD is written without target intrinsics.

`spec/13-gnu-compat.md` does not list the vector extensions among the ones it turns down, so this is a gap rather than a decision.

**Comment by tamnd** [comment]
This is worth re-reading as a miscompilation rather than as a missing feature, because that is what it currently is.

`__attribute__((vector_size (n)))` is not rejected and not warned about. It is dropped, and the type keeps the width of its element:

```c
typedef int __attribute__((vector_size (16))) vecint;
int f(void) { return sizeof(vecint); }
```

returns 4, where gcc 16.2.0 returns 16. Everything downstream follows from that. An object of the type is four bytes instead of sixteen, an array of them is a quarter of the size it should be, `+` on two of them adds the first element and leaves the other three, and a program that reads the rest of the vector reads whatever is next to it.

`gcc.c-torture/execute/simd-1.c` and `simd-2.c` are the clearest demonstration. They are written to work on a target with no SIMD instructions at all, so nothing about them needs vector hardware, and they abort on the first comparison because the arithmetic did not happen to the values they think it happened to.

Until #320 those two were refused for something else, so nothing here was reachable. #320 takes that refusal away, and the two now build and abort. That is not a regression in #320, it is this issue arriving in the corpus, but it does mean there is a program in the corpus today whose wrong answer is this attribute rather than anything else.

Whatever the eventual implementation is, refusing the attribute is strictly better than dropping it, and it is much smaller. A program that uses `vector_size` and gets told this compiler does not implement it can be built with gcc. A program that uses it and gets a quarter of its data silently cannot be trusted at all, and there is no diagnostic anywhere for the author to notice. So a diagnostic on the attribute is worth doing first and separately from the feature, and this is why the labels now say miscompilation and p1.

**Comment by tamnd** [comment]
The first execution sweep over gcc-torture says something this issue did not know: a vector does not always fail to build. Twelve programs get all the way through, run, and abort.

- `execute/20050316-1.c`, `execute/20050316-2.c`, `execute/20050316-3.c`, `execute/20050604-1.c`
- `execute/pr92618.c`
- `execute/scal-to-vec1.c`, `execute/scal-to-vec2.c`, `execute/scal-to-vec3.c`
- `execute/simd-1.c`, `execute/simd-2.c`, `execute/simd-4.c`, `execute/simd-6.c`

Twenty five others still stop at the front end, on `subscripted value is neither array nor pointer nor vector`, which is what this issue was filed about and is still the larger number.

The twelve are the more serious half. A type the compiler refuses is a compiler that says so. A type the compiler accepts, lays out as something else and does arithmetic on as something else is a program that runs and is wrong, and none of these twelve prints anything to say it happened. Whatever partial support exists today is worse than none, and it is worth deciding early whether the answer is to finish the feature or to refuse the attribute outright until it is finished.

The exec exclusion list in `tamnd/rucc-compat` names all twelve against this issue with an outcome of `crashed`, so they stop being excused the day any of them starts passing.

**Comment by tamnd** [comment]
The type is built and the arithmetic is right. #480 and tamnd/rucc-compat#67 landed the first half.

`int __attribute__((vector_size(16)))` is four `int` in a row rather than an `int` with an attribute walked past. Every operator over one means that operator on each lane, a scalar beside a vector stands for itself in every lane, a subscript reads one lane, and a cast between a vector and anything of the same size reinterprets the bytes. A lane narrower than an `int` is computed at `int` and truncated back, since C promotes a `short` before any operator sees it.

Twelve programs in the gcc torture suite were being compiled as the lane type and getting a wrong answer out of it, which is a miscompilation and not a missing feature, and they are correct now at every level the harness runs. Eleven more came off the exclusion list at the same time because they turned out to pass once the entry stopped preventing the harness from compiling them.

What is left, each measured by removing the exclusion and reading the error rather than guessed at.

- A comparison of two vectors has no result type, E0508. `a > b` should give a vector of masks, all ones for true, with the same lane count and a signed integer lane of the same width. Seven cases.
- One lane is readable and is not assignable, E0506. `v[0] = x` is refused. Two cases.
- A compound literal of vector type is not built, E0515 or E0571, including the empty one. Three cases.
- A vector has no increment or decrement, E0509. One case.
- `__builtin_shuffle` and `__builtin_shufflevector` are not implemented, which the description above already named and which nothing in the torture suite blocks on today.

Beyond the front end, and not a case count. A vector lives in memory and its lanes are computed one at a time, which is correct arithmetic and is not the instruction the machine has. The IR can spell a vector and no lowering rule is written at a lane count, so a vector held as a value would be a value nothing could select on. Holding one in a register, and passing one where the psABI puts it rather than as the lanes it is made of, are the two pieces that make this fast rather than merely right, and a vector of pointers has no lowering either.

The order to do them in is the case count: comparisons, then compound literals, then lane assignment, then increment. All four are front end work and none of them needs the register question answered first.

**Comment by tamnd** [comment]
Comparisons are done, in #494.

A comparison of two vectors is the one operator over them whose answer is not the type of its operands. `a < b` now gives a vector of the signed integers of the lane width, all ones in each lane where the comparison held and zero where it did not, so what comes back is a value to mask with rather than a condition to branch on. That is what a program does with one, since `(a > b) & a` is written far more often than the result is tested. Comparing `unsigned int` lanes answers in `int` lanes and comparing `float` lanes answers in `int` lanes as well, which is the pair of types the lowering has to keep apart, since the lanes it reads are not the lanes it writes.

The mask has a type its own operands cannot hold, so GNU's lax vector conversion came with it: two vectors of the same size convert between each other by reinterpreting the bytes, which is what gcc's `vector_types_convertible_p` decides. Without that a comparison of two `unsigned int` vectors could not be assigned back to one.

Each lane comes out as the comparison, a zero extension of the one bit it gives, and zero minus that. A sign extension out of one bit would be one instruction fewer and the same value, but no rule set lowers one today and it would be a rule per target for something the optimizer folds back anyway.

Checked against gcc 16.2.0 on a probe covering signed, unsigned and float lanes plus a mask used as a mask, and both compilers print the same thing. Seven torture cases were excluded for this: five pass now and the other two need something else, `pr105613` an `__int128` which is #351, and `pr108292` the address of one lane which is the next item here. The corpus change is tamnd/rucc-compat#68.

Three gaps left, in the order the case count puts them in: a compound literal of a vector, assigning to one lane, and incrementing one. All three are front end work. After those, what is left is holding a vector in a register and passing one where the psABI puts it rather than as the lanes it is made of, which is the back end half and needs the register question answered first.

**Comment by tamnd** [comment]
Compound literals are done, in #502.

Two things that turned out to be the same one. A vector takes a braced list the way an array of its lanes does and is also a value, which an array is not, and the two readings meet inside an array of vectors. `V a[] = { (V){1,2}, (V){3,4} }` is two vectors and `V a[2] = { 1, 2, 3, 4 }` is the same four lanes with the braces left out, so the type of the element that was written is what says which was meant. That is the rule a `struct` already followed, and the vector case was falling through to the array arm below it, which descends, so the whole vector arrived at the first lane and was reported as a bad initializer for an `int`.

And `vector_size` is now read on a type name and not only on a declaration. A cast and a compound literal are where a macro that takes a lane type and a lane count writes the attribute out rather than naming a typedef, so `(int __attribute__((vector_size(32)))){ 5, 6, 7, 8 }` was an `int` before this.

Three torture cases were excluded for it. `pr123625` passes. `pr53645` and `pr53645-2` get past the walk and stop at the inline assembly in them, so they moved to #349. The corpus change is tamnd/rucc-compat#69.

`check gcc-torture` reports 1772 cases, 1626 passed, 146 excluded, 0 failing, 0 stale, and the `-O0` sweep over all three corpora is clean.

Two gaps left in the front end, in the order the case count puts them in: assigning to one lane, which is three cases, and incrementing one, which is one. `pr108292` also wants a shift of two vectors whose lanes differ in signedness, which the lanewise path does not take yet, and that is small enough to go with the lane assignment. After those, what is left is the back end half: holding a vector in a register and passing one where the psABI puts it.

**Comment by tamnd** [comment]
Lane assignment is done, in #512, and the mixed shift went with it as planned.

A vector is an object rather than a value, so a subscript of one is an lvalue whenever the vector it came from is. The subscript was reading its base as a value first, which is what every other base has to take because an array decays to a pointer and a vector does not, and reading it left nothing with an object behind it to assign to. Not reading it makes `v[0] = n`, `v[0] += n`, `v[0]++` and `&v[0]` all mean what they say. A qualifier written on the vector reaches every lane the way it does on an array, so `const V v` still has no lane to write to, which is why the lane type is qualified there rather than left as the element was built.

The shift turned out to be the more interesting half. It is the one lanewise operator whose two sides are not brought to a single type, because the right side is a count rather than a value: the answer is the type of the left side, and all that is asked of a vector of counts is that it holds integers and has as many lanes as the vector being shifted. That is what lets a vector of `unsigned` be shifted by the signed mask a comparison gave. I had it refusing a scalar on the left first, on the theory that a count cannot decide the shape of the answer, and `scal-to-vec1` says otherwise: it writes `2 << v` and `v << 2` on consecutive lines and expects both, so a scalar stands for itself in every lane on either side. The lowering reads the count with its own lane type and its own stride, since the two vectors may disagree about the lane.

Three torture cases were excluded for the lane assignment. `pr126405-3` and `pr85169` pass. `pr108292` wants all of this and `__builtin_sub_overflow` as well, so it moved to #309. The corpus change is tamnd/rucc-compat#70.

`check gcc-torture` reports 1772 cases, 1628 passed, 144 excluded, 0 failing, 0 stale, and the `-O0` sweep over all three corpora is clean.

One gap left in the front end: incrementing a whole vector, which is `pr123753` and is one case. After that, what is left is the back end half, holding a vector in a register and passing one where the psABI puts it.

**Comment by tamnd** [comment]
The last front end gap is closed, in #519. A whole vector steps by one now, so `++v`, `--v`, `v++` and `v--` are the lane's step taken in every lane.

The operand rule every other step follows asks for an arithmetic type or a pointer, which a vector is neither of, and that is where all four were being refused. GNU allows them and has to, since a vector of counters is what the operator is for. The prefix and postfix forms differ where they always do: what a prefix one is worth is the object after the step and what a postfix one is worth is what was in it before, which is a copy, and a copy of a vector lives in memory the way every computed vector does. So the copy is made where the value is asked for and nowhere else, and `v++;` written as a statement steps the object and copies nothing.

`pr123753` is the case and it prints what gcc 16.2.0 prints. So does a probe that steps a vector of `float` lanes, where the step is an addition of one rather than a bit pattern away from it. The corpus change is tamnd/rucc-compat#71.

`check gcc-torture` reports 1772 cases, 1629 passed, 143 excluded, 0 failing, 0 stale. The `-O0` sweep is 5316 runs, 4061 passed, 0 wrong answer, 0 crashed, 0 did not build, 754 excluded, 0 stale.

What is left here is the back end half, holding a vector in a register and passing one where the psABI puts it. Every operator over one is correct arithmetic today and none of it is the instruction the machine has.
