### ISSUE TITLE
A #pragma once in the main file is warned about and then dropped

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc#193]
`#pragma once` in the file named on the command line is warned about and then not applied. The warning is fine, since the line in a main file usually means a header that ended up being compiled on its own, but gcc warns and applies it, and the case where it matters in a main file is the file that includes itself.

chibicc's `test/pragma-once.c` is that file:

```c
#include "test.h"

#pragma once

#include "test/pragma-once.c"

int main() {
  printf("OK\n");
  return 0;
}
```

gcc 16 accepts it and its `-E` output holds one `int main`. rucc reads the file twice and reports a redefinition of `main`.

There is a second half to this. The multiple-include optimization records a file under the name the include used, so the same header reached through two include directories is two files, read in full each time, each with its guard recorded separately. `spec/05-preprocessor.md` section 5.3 has claimed since it was written that both `#pragma once` and the guard optimization work on file identity rather than on the name, and the implementation never did. The chibicc case runs into both at once, because the harness makes the include path absolute and the file on the command line is relative, so even a `#pragma once` that was applied would not match the second name.
