### ISSUE TITLE
a template naming the high byte of a register, which is how femtolisp swaps two bytes

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc#1654]
femtolisp is on the R3 checklist as done and it does not build. The flag wall that #1570 cleared was real and is gone, and what is behind it is a different thing entirely, so the checkbox is about the flag rather than about the project. The error is at the first file every other file of the library includes:

```
llt/utils.h:44:3: error: cannot generate code for 'ByteSwap16': this `asm` has instructions in its template, which nothing here assembles [E0653]
```

The line is the ordinary way a C library written before `__builtin_bswap16` swaps two bytes:

```c
#ifdef ARCH_X86_64
#  define LEGACY_REGS "=Q"
#else
#  define LEGACY_REGS "=q"
#endif

STATIC_INLINE u_int16_t ByteSwap16(u_int16_t x)
{
  __asm("xchgb %b0,%h0" :
        LEGACY_REGS (x)	:
        "0" (x));
    return x;
}
```

This is not a regression from #1653. The released 0.10.74 binary gives the identical error on the identical line, so the ladder record has been stale since femtolisp went on it.

## The two things it wants, which are separate

**One, `%h`.** `%b0` and `%h0` are the low byte and the high byte of the same operand's register. `crates/rucc-target/src/x86_64/read.rs` reads four modifiers, `%b`, `%w`, `%k` and `%q`, which are the byte, the word, the long and the quad of a register, and the module doc says why `%h` is not among them: it names a register rather than a part of one, and nothing in this backend has a name for it. That is still true. The only `ah` anywhere in the target is one hardcoded string in `crates/rucc-target/src/x86_64/text.rs:313`, which moves the remainder of an eight bit division down out of the high half, and it is text rather than a register the allocator can hand out or a class anything can ask for. So answering `%h` means the machine growing four registers it does not have, `ah`, `bh`, `ch` and `dh`, each of which is a name for part of a register that already exists, which the allocator's model of a register has no notion of.

**Two, `xchg` between two registers.** Even with `%h` read, the line does not assemble. The machine has `xchg_8`, `xchg_16`, `xchg_32` and `xchg_64` and every one of them is `Rmw`, a register exchanged with memory, because that is the form anything here has ever asked for. `xchgb %b0,%h0` is a register exchanged with a register, and the lookup in `read.rs` matches the shapes the written form gives, so it finds nothing and the template is refused before the modifier is ever looked at.

## What is worth deciding before either

`Q` is the constraint asking for one of the four registers that have a high byte, and nothing here reads it as anything narrower than the ordinary byte class, so a program that writes `%h` today could be handed `%sil` and have nowhere to put the modifier even if the modifier were read. The constraint and the modifier are one question rather than two.

The other question is whether this is worth doing as a machine change at all, or whether the pattern is common enough to recognise. `xchgb %b0,%h0` on a sixteen bit value is a byte swap and nothing else, and both gcc and clang lower it to `rolw $8` or `xchg` on their own when the program writes `__builtin_bswap16`. Recognising the pair would get femtolisp building without the allocator ever learning what a high byte is. That is a narrower fix and a worse one, because the next program writes the same registers for something that is not a swap, and this compiler's rule for a template has been to read what the program wrote rather than to guess at what it meant. Worth saying out loud and deciding rather than sliding into.

Part of #349.
